version: "3.9"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
	  depends_on: wordpress
    ports:
      - "443:443"
    restart: always
    networks:
      - common
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
        - ./mariadb/tools/volumes:/var/lib/mysql
    restart: always
    networks:
        - common
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - ./wordpress/tools/volumes:/var/www/html
    restart: always
    depends_on: mariadb
    networks:
      - common
networks: 
  common:
    driver: bridge