version: "3.9"
services:
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - type: volume
        source: wp_data
        target: /opt/wordpress
    depends_on:
      - mariadb
    ports:
      - "443:443"
    restart: always
    networks:
      - common
  mariadb:
    container_name: mariadb
    build: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - common
  wordpress:
    container_name: wordpress
    build: wordpress
    volumes:
      - type: bind
        source: ./wordpress/tools/wp-config.php
        target: /opt/wordpress/wp-config.php
      - type: volume
        source: wp_data
        target: /opt/wordpress
    # volumes:
    #  - ./wordpress/volumes:/opt/wordpress
    restart: always
    ports:
      - "9000:9000"
    
    depends_on:
       - nginx
    networks:
      - common
networks: 
  common:
    driver: bridge
volumes:
  wp_data:
    # source: ./wordpress/volumes
